image:
    tag: v0.1.3

replicas: 1

service:
    type: NodePort
    port: 80
    targetPort: 8080
    #NodePort: 30001

ingress: 
    hosts: hipster-shop.itbegin.ru
    serviceName: frontend
    servicePort: 80