apiVersion: apps/v1
kind: Deployment
metadata:
  name: web                             # Название нашего объекта Deployment
spec:
  replicas: 3                           # Начнем с одного пода
  selector:                             # Укажем, какие поды относятся к нашему Deployment:
    matchLabels:                        # - это поды с меткой
      app: web                          # app и ее значением web
  strategy:                             # Задаем стратегию обновления 
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 100%
  template:                             # Теперь зададим шаблон конфигурации пода
    metadata:
      name: web                         # Название Pod
      labels: 
        app: web                        # Метки в формате key: value
    spec:                               # Описание Pod
      initContainers: 
        - name: html-gen
          image: busybox:musl
          command: ['sh', '-c', 'wget -O- https://bit.ly/otus-k8s-index-gen | sh']
          volumeMounts: 
            - name: app
              mountPath: /app
      containers:                       # Описание контейнеров внутри Pod
        - name: web                     # Название контейнера
          image: linarnadyrov/kubernetes-intro:1.1
          readinessProbe:               # Добаим проверку готовности
            httpGet:                    # веб-сервера отдавать
              path: /index.html         # контент 
              port: 8000
          livenessProbe: 
            tcpSocket:
              port: 8000
          volumeMounts: 
            - name: app
              mountPath: /app
      volumes: 
        - name: app
          emptyDir: {}

