# Установка и настройка docker на OC Ubuntu (arch=amd64)
---
- hosts: all
  remote_user: LinarNadyrov
  become: yes
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
  # sudo apt-get install *
  - name: Install docker packages
    apt:
      name: "{{ item }}"
      state: present
      update_cache: yes
    with_items:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - gnupg2
      - nano
      - mc

  # curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - name: Add Docker s official GPG key
    apt_key:
      url: https://download.docker.com/linux/ubuntu/gpg
      state: present
  
  # sudo apt-key fingerprint 0EBFCD88
  - name: Verify that we have the key with the fingerprint
    apt_key:
      id: 0EBFCD88
      state: present

  # sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable"
  - name: Set up the stable repository
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} stable
      #xenial stable
      state: present
      update_cache: yes

  # sudo apt-get update
  - name: Update apt packages
    apt:
      update_cache: yes
  
  # sudo apt-get install docker

  - name: Install docker
    shell: | 
      apt-get install -y \
      containerd.io=1.2.13-1 \
      docker-ce=5:19.03.8~3-0~ubuntu-$(lsb_release -cs) \
      docker-ce-cli=5:19.03.8~3-0~ubuntu-$(lsb_release -cs)
    notify: restart docker

  - name: Change storage-driver
    shell: | 
      cat > /etc/docker/daemon.json <<EOF
      {
          "exec-opts": ["native.cgroupdriver=systemd"],
          "log-driver": "json-file",
          "log-opts": {
              "max-size": "100m"
          },
          "storage-driver": "overlay2"
      }
      EOF

  - name: Added gpg key
    shell: | 
      curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key add -
  
  - name: Added sources.list
    shell: | 
      cat > /etc/apt/sources.list.d/kubernetes.list <<EOF
      deb https://apt.kubernetes.io/ kubernetes-xenial main
        
    # sudo apt-get update
  - name: Update apt packages
    apt:
      update_cache: yes

  - name: Install kubeadm, kubectl, kubelet
    shell: | 
      apt-get install -y \
      kubelet=1.17.4-00 \ 
      kubeadm=1.17.4-00 \ 
      kubectl=1.17.4-00 

  handlers:
  - name: restart docker
    systemd:
      name: docker
      state: restarted