apiVersion: v1          # Версия API
kind: Pod               # Объект, который создаем
metadata:
  name: web             # Название Pod
  labels: 
    app: web            # Метки в формате key: value
spec:                   # Описание Pod
  initContainers: 
    - name: init-web
      image: busybox:1.31.0
      command: ['sh', '-c', 'wget -O- https://tinyurl.com/otus-k8s-intro | sh']
      volumeMounts: 
        - name: app
          mountPath: /app
  containers:           # Описание контейнеров внутри Pod
    - name: web         # Название контейнера
      image: linarnadyrov/kubernetes-intro:1.1
      volumeMounts: 
        - name: app
          mountPath: /app
  volumes: 
    - name: app
      emptyDir: {} 